server:
    port: 9005

eureka:
    instance:
        prefer-ip-address: true
        hostname: eureka-0
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka
        register-with-eureka: true
        fetch-registry: true

spring:
    application:
        name: notification-service
    kafka:
        bootstrap-servers: broker:9092
        template:
            default-topic: notification
        consumer:
            group-id: notificationId
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.type.mapping: event:com.procheck.notificationservice.ReceptionPlacedEvent

management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans/
    tracing:
        sampling:
            probability: 1
    endpoints:
        web:
            exposure:
                include: health, prometheus, metrics, info
    endpoint:
        health:
            show-details: always
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"