apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://212.237.231.147:3306/xui
            - name: SPRING_DATASOURCE_USERNAME
              value: "yahya"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "yahya"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: alismak/user-service:latest
          name: user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9009
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-svc
  name: user-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9009
  selector:
    app: user-service
